title: MauBNC
subtitle: Proyek BNC Gratis
email: bnc@goez.my.id
description: >- # this means to ignore newlines until "baseurl:"
  MauBNC adalah salah satu penyedia Bouncers Gratis yang menggunakan platform ZNC. MauBNC di dirikan oleh seorang user biasa yang sangat hobi dengan IRC, dan ini hanya untuk berbagi dengan Anda :).
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: maubncga
github_username:  maubnc

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
